### ISSUE TITLE
Chapter references

### ISSUE THREAD

**Issue by chnaccarato** [LingConLab/TALD_manual#11]
Our page [How to write a chapter](https://lingconlab.github.io/TALD_manual/chapters.html) says that, when compiling the table with the chapter references, we should do the following:

"When adding values to the TITLE and BOOKTITLE fields, you need to surround capital letters that are not at the beginning of the word with curly brackets, for example Volume {IV}. This is necessary so that such cases do not change to Volume Iv after rendering."

But it seems that we fixed this already and this is not necessary anymore. Can we remove this sentence from the page?
@agricolamz

**Comment by agricolamz** [comment]
Sure!
