### ISSUE TITLE
chapter template

### ISSUE THREAD

**Issue by agricolamz** [LingConLab/TALD_manual#8]
- [x] remove the numeration in headers `## 1. Introduction` -> `## Introduction`
- [x] change table links from `#m..` to `#t...`
- [x] change number of hashes to 5 `#####`
- [x] add an example of multiline example
- [x] the `make_gloss_list()` should be rewritten, you shouldn't use the `add_gloss()` function anywhere except in tables
- [x] Section `Adding new literature` should contain information about translation. Transliteration is made automatically, so remove info about it from the text.
- [x] Add info about numeric variables to the map section.

**Comment by timtim1342** [comment]
> change number of hashes to 5 #####

Надо видимо пройтись по главам и проверить, что везде 5. Сейчас не везде так:

![image](https://user-images.githubusercontent.com/31654783/189478647-85aa88a2-5eae-4f7e-bbaa-052f5630f39a.png)

**Comment by agricolamz** [comment]
я в какой-то момент это делал, но, возможно невнимательно.

**Comment by timtim1342** [comment]
Гарик, а можешь пояснить последние три пункта?

> Section Adding new literature should contain information about translation. 

Тут речь про страницу Datasets? Переводить нужно название работы и город в адресе, все?

> Transliteration is made automatically, so remove info about it from the text.

То есть раздел Transcription на Datasets?

>  Add info about numeric variables to the map section.

Что формат ячеек в таблице должен быть числовой? Или это про то, что не должно быть много значений?

> the make_gloss_list() should be rewritten

В смысле перенести после вызова `add_gloss()`? Про исправлении/добавление глосс не нужен параграф же, их добавляет не автор? Как это сейчас устроено?

**Comment by agricolamz** [comment]
> Section Adding new literature should contain information about translation.

Это про то, что должен быть перевод заголовков title и книг booktitle. А также город, да.

> То есть раздел Transcription на Datasets?

Не понял вопроса, транскрипция вроде должна быть едина настолько, насколько это возможно.

> Что формат ячеек в таблице должен быть числовой? Или это про то, что не должно быть много значений?
Что формат **может** быть числовым. И что не нужно много значений тоже нужно написать.

> В смысле перенести после вызова add_gloss()? Про исправлении/добавление глосс не нужен параграф же, их добавляет не автор? Как это сейчас устроено?

Их добавляет автор в таблицу glosses.xlsx или как-то аналогично. Нужно обсудить неправильные глоссы, если, например, там что-нибудь автоматически неправильно подбирает, что в таком случае делать и т. п. `add_glosses()` для создания списка глосс мы не используем.
